### PR TITLE
nnSent output fixed

### PR DESCRIPTION
**Pull request by Gldkslfmsd**
nnSent command didn't get any output before because of several programming bugs (wrong index in cmd line parsing, wrong reading of corpus length). I fixed it and tested nnSent on small corpus, cca 15 sentences. There can still be bugs in other commands...

I also slightly changed output format, I like it more this way.

### CODE REVIEW

**Comment by martinjaggi** [comment]
looks good!
can you remove the outcommented lines again? (good to print the number of sentences though) and throw an error message when no sentence file is given?

**Comment by Gldkslfmsd** [comment]
> can you remove the outcommented lines again? (good to print the number of sentences though)

I don't know what you mean.

> throw an error message when no sentence file is given?

yes, I can, maybe later today

**Comment by Gldkslfmsd** [comment]
> >  throw an error message when no sentence file is given?
> yes, I can, maybe later today

Sorry, I don't have time for it.

BTW., greetings from MT Marathon :)

**Comment by guptaprkhr** [comment]
Hi Martin, the required changes have been done.

**Comment by martinjaggi** [comment]
thanks a lot!

**Pull request merged**
